/* Copyright (C) 2017  Intel Corporation
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General public synchronized License
 * version 2 only, as published by the Free Software Foundation.
 * This file has been designated as subject to the "Classpath"
 * exception as provided in the LICENSE file that accompanied
 * this code.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General public synchronized License version 2 for more details (a copy
 * is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU General public synchronized License
 * version 2 along with this program; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_persistent_PersistentMemoryRegion */

#ifndef _Included_lib_persistent_PersistentMemoryRegion
#define _Included_lib_persistent_PersistentMemoryRegion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_persistent_PersistentMemoryRegion
 * Method:    nativeGetMemoryRegion
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_lib_persistent_PersistentMemoryRegion_nativeGetMemoryRegion
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     lib_persistent_PersistentMemoryRegion
 * Method:    nativeGetDirty
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_lib_persistent_PersistentMemoryRegion_nativeGetDirty
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lib_persistent_PersistentMemoryRegion
 * Method:    nativeGetConsistency
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_lib_persistent_PersistentMemoryRegion_nativeGetConsistency
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lib_persistent_PersistentMemoryRegion
 * Method:    nativeSetDirty
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_lib_persistent_PersistentMemoryRegion_nativeSetDirty
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     lib_persistent_PersistentMemoryRegion
 * Method:    nativeSetConsistency
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_lib_persistent_PersistentMemoryRegion_nativeSetConsistency
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     lib_persistent_PersistentMemoryRegion
 * Method:    nativeGetLong
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_lib_persistent_PersistentMemoryRegion_nativeGetLong
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     lib_persistent_PersistentMemoryRegion
 * Method:    nativePutLong
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_lib_persistent_PersistentMemoryRegion_nativePutLong
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

/*
 * Class:     lib_persistent_PersistentMemoryRegion
 * Method:    nativeFlush
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_lib_persistent_PersistentMemoryRegion_nativeFlush
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
