/* Copyright (C) 2016  Intel Corporation
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 only, as published by the Free Software Foundation.
 * This file has been designated as subject to the "Classpath"
 * exception as provided in the LICENSE file that accompanied
 * this code.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details (a copy
 * is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with this program; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_persistent_Util */

#ifndef _Included_lib_persistent_Util
#define _Included_lib_persistent_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_persistent_Util
 * Method:    nativeOpenPool
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lib_persistent_Util_nativeOpenPool
  (JNIEnv *, jclass);

/*
 * Class:     lib_persistent_Util
 * Method:    nativeGetRoot
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_lib_persistent_Util_nativeGetRoot
  (JNIEnv *, jclass);

/*
 * Class:     lib_persistent_Util
 * Method:    nativeDebugPool
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_lib_persistent_Util_nativeDebugPool
  (JNIEnv *, jclass, jint);

/*
 * Class:     lib_persistent_Util
 * Method:    nativeRegisterOffset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_lib_persistent_Util_nativeRegisterOffset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     lib_persistent_Util
 * Method:    nativeDeregisterOffset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_lib_persistent_Util_nativeDeregisterOffset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     lib_persistent_Util
 * Method:    nativeDecRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_lib_persistent_Util_nativeDecRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     lib_persistent_Util
 * Method:    nativeIncRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_lib_persistent_Util_nativeIncRef
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
