/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_persistent_PersistentLong */

#ifndef _Included_lib_persistent_PersistentLong
#define _Included_lib_persistent_PersistentLong
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_persistent_PersistentLong
 * Method:    nativeSetLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_lib_persistent_PersistentLong_nativeSetLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lib_persistent_PersistentLong
 * Method:    nativeGetLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_lib_persistent_PersistentLong_nativeGetLong
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
