/* Copyright (C) 2017  Intel Corporation
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 only, as published by the Free Software Foundation.
 * This file has been designated as subject to the "Classpath"
 * exception as provided in the LICENSE file that accompanied
 * this code.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details (a copy
 * is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with this program; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_xpersistent_XRoot */

#ifndef _Included_lib_xpersistent_XRoot
#define _Included_lib_xpersistent_XRoot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_xpersistent_XRoot
 * Method:    nativeRootExists
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_lib_xpersistent_XRoot_nativeRootExists
  (JNIEnv *, jclass);

/*
 * Class:     lib_xpersistent_XRoot
 * Method:    nativeGetRootOffset
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_lib_xpersistent_XRoot_nativeGetRootOffset
  (JNIEnv *, jclass);

/*
 * Class:     lib_xpersistent_XRoot
 * Method:    nativeCreateRoot
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_lib_xpersistent_XRoot_nativeCreateRoot
  (JNIEnv *, jclass, jlong);

/*
 * Class:     lib_xpersistent_XRoot
 * Method:    nativeAllocateHashmap
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_lib_xpersistent_XRoot_nativeAllocateHashmap
  (JNIEnv *, jclass);

/*
 * Class:     lib_xpersistent_XRoot
 * Method:    nativeHashmapPut
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_lib_xpersistent_XRoot_nativeHashmapPut
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     lib_xpersistent_XRoot
 * Method:    nativeHashmapGet
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_lib_xpersistent_XRoot_nativeHashmapGet
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     lib_xpersistent_XRoot
 * Method:    nativeHashmapRemove
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_lib_xpersistent_XRoot_nativeHashmapRemove
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     lib_xpersistent_XRoot
 * Method:    nativeHashmapDebug
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_lib_xpersistent_XRoot_nativeHashmapDebug
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lib_xpersistent_XRoot
 * Method:    nativeHashmapClear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_lib_xpersistent_XRoot_nativeHashmapClear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lib_xpersistent_XRoot
 * Method:    nativePrintAllObjects
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_lib_xpersistent_XRoot_nativePrintAllObjects
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     lib_xpersistent_XRoot
 * Method:    nativeCleanVMOffsets
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_lib_xpersistent_XRoot_nativeCleanVMOffsets
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     lib_xpersistent_XRoot
 * Method:    nativeImportCandidates
 * Signature: (JLjava/util/HashSet;)V
 */
JNIEXPORT void JNICALL Java_lib_xpersistent_XRoot_nativeImportCandidates
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
