/* Copyright (C) 2017  Intel Corporation
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 only, as published by the Free Software Foundation.
 * This file has been designated as subject to the "Classpath"
 * exception as provided in the LICENSE file that accompanied
 * this code.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details (a copy
 * is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with this program; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_xpersistent_XHeap */

#ifndef _Included_lib_xpersistent_XHeap
#define _Included_lib_xpersistent_XHeap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_xpersistent_XHeap
 * Method:    nativeOpenHeap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lib_xpersistent_XHeap_nativeOpenHeap
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     lib_xpersistent_XHeap
 * Method:    nativeCloseHeap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lib_xpersistent_XHeap_nativeCloseHeap
  (JNIEnv *, jobject);

/*
 * Class:     lib_xpersistent_XHeap
 * Method:    nativeAllocate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_lib_xpersistent_XHeap_nativeAllocate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lib_xpersistent_XHeap
 * Method:    nativeFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_lib_xpersistent_XHeap_nativeFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lib_xpersistent_XHeap
 * Method:    nativeMemoryRegionMemcpy
 * Signature: (JJJJJ)V
 */
JNIEXPORT void JNICALL Java_lib_xpersistent_XHeap_nativeMemoryRegionMemcpy
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     lib_xpersistent_XHeap
 * Method:    nativeToByteArrayMemcpy
 * Signature: (JJ[BII)V
 */
JNIEXPORT void JNICALL Java_lib_xpersistent_XHeap_nativeToByteArrayMemcpy
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     lib_xpersistent_XHeap
 * Method:    nativeFromByteArrayMemcpy
 * Signature: ([BIJJI)V
 */
JNIEXPORT void JNICALL Java_lib_xpersistent_XHeap_nativeFromByteArrayMemcpy
  (JNIEnv *, jobject, jbyteArray, jint, jlong, jlong, jint);

/*
 * Class:     lib_xpersistent_XHeap
 * Method:    nativeDebugPool
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_lib_xpersistent_XHeap_nativeDebugPool
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
