/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_llpl_Heap */

#ifndef _Included_lib_llpl_Heap
#define _Included_lib_llpl_Heap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_llpl_Heap
 * Method:    nativeGetMemoryRegion
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_lib_llpl_Heap_nativeAllocate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lib_llpl_Heap
 * Method:    nativeOpenHeap
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_lib_llpl_Heap_nativeOpenHeap
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     lib_llpl_Heap
 * Method:    nativeSetRoot
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_lib_llpl_Heap_nativeSetRoot
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lib_llpl_Heap
 * Method:    nativeRealloc
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_lib_llpl_Heap_nativeRealloc
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     lib_llpl_Heap
 * Method:    nativeGetRoot
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_lib_llpl_Heap_nativeGetRoot
  (JNIEnv *, jobject);

/*
 * Class:     lib_llpl_Heap
 * Method:    nativeFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_lib_llpl_Heap_nativeFree
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
