/* Copyright (C) 2017  Intel Corporation
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 only, as published by the Free Software Foundation.
 * This file has been designated as subject to the "Classpath"
 * exception as provided in the LICENSE file that accompanied
 * this code.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details (a copy
 * is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with this program; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_llpl_Heap */

#ifndef _Included_lib_llpl_Heap
#define _Included_lib_llpl_Heap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_llpl_Heap
 * Method:    nativeOpenHeap
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_lib_llpl_Heap_nativeOpenHeap
  (JNIEnv *, jobject, jstring);

/*
 * Class:     lib_llpl_Heap
 * Method:    nativeGetMemoryRegion
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_lib_llpl_Heap_nativeGetMemoryRegion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lib_llpl_Heap
 * Method:    nativeSetRoot
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_lib_llpl_Heap_nativeSetRoot
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lib_llpl_Heap
 * Method:    nativeGetRoot
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_lib_llpl_Heap_nativeGetRoot
  (JNIEnv *, jobject);

/*
 * Class:     lib_llpl_Heap
 * Method:    nativeFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_lib_llpl_Heap_nativeFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lib_llpl_Heap
 * Method:    nativeFlush
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_lib_llpl_Heap_nativeFlush
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
