/* Copyright (C) 2017  Intel Corporation
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 only, as published by the Free Software Foundation.
 * This file has been designated as subject to the "Classpath"
 * exception as provided in the LICENSE file that accompanied
 * this code.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details (a copy
 * is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with this program; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_llpl_Transaction */

#ifndef _Included_lib_llpl_Transaction
#define _Included_lib_llpl_Transaction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_llpl_Transaction
 * Method:    nativeStartTransaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lib_llpl_Transaction_nativeStartTransaction
  (JNIEnv *, jobject);

/*
 * Class:     lib_llpl_Transaction
 * Method:    nativeEndTransaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lib_llpl_Transaction_nativeEndTransaction
  (JNIEnv *, jobject);

/*
 * Class:     lib_llpl_Transaction
 * Method:    nativeAbortTransaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lib_llpl_Transaction_nativeAbortTransaction
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
