/* Copyright (C) 2017  Intel Corporation
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 only, as published by the Free Software Foundation.
 * This file has been designated as subject to the "Classpath"
 * exception as provided in the LICENSE file that accompanied
 * this code.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details (a copy
 * is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with this program; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_llpl_TransactionalMemoryRegion */

#ifndef _Included_lib_llpl_TransactionalMemoryRegion
#define _Included_lib_llpl_TransactionalMemoryRegion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_llpl_TransactionalMemoryRegion
 * Method:    nativePutBits
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_lib_llpl_TransactionalMemoryRegion_nativePutBits
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

/*
 * Class:     lib_llpl_TransactionalMemoryRegion
 * Method:    nativeMemoryRegionMemcpyTransactional
 * Signature: (JJJJJ)I
 */
JNIEXPORT jint JNICALL Java_lib_llpl_TransactionalMemoryRegion_nativeMemoryRegionMemcpyTransactional
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     lib_llpl_TransactionalMemoryRegion
 * Method:    nativeFromByteArrayMemcpyTransactional
 * Signature: ([BIJJI)I
 */
JNIEXPORT jint JNICALL Java_lib_llpl_TransactionalMemoryRegion_nativeFromByteArrayMemcpyTransactional
  (JNIEnv *, jobject, jbyteArray, jint, jlong, jlong, jint);

/*
 * Class:     lib_llpl_TransactionalMemoryRegion
 * Method:    nativeMemoryRegionMemsetTransactional
 * Signature: (JJIJ)I
 */
JNIEXPORT jint JNICALL Java_lib_llpl_TransactionalMemoryRegion_nativeMemoryRegionMemsetTransactional
  (JNIEnv *, jobject, jlong, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
