/* Copyright (C) 2017  Intel Corporation
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 only, as published by the Free Software Foundation.
 * This file has been designated as subject to the "Classpath"
 * exception as provided in the LICENSE file that accompanied
 * this code.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details (a copy
 * is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with this program; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_llpl_FlushableMemoryRegion */

#ifndef _Included_lib_llpl_FlushableMemoryRegion
#define _Included_lib_llpl_FlushableMemoryRegion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_llpl_FlushableMemoryRegion
 * Method:    nativeFlush
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_lib_llpl_FlushableMemoryRegion_nativeFlush
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     lib_llpl_FlushableMemoryRegion
 * Method:    nativePutBits
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_lib_llpl_FlushableMemoryRegion_nativePutBits
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

/*
 * Class:     lib_llpl_FlushableMemoryRegion
 * Method:    nativeSetFlushed
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_lib_llpl_FlushableMemoryRegion_nativeSetFlushed
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     lib_llpl_FlushableMemoryRegion
 * Method:    nativeGetVolatileAddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_lib_llpl_FlushableMemoryRegion_nativeGetVolatileAddress
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
