/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_vmem_XMemory */

#ifndef _Included_lib_vmem_XMemory
#define _Included_lib_vmem_XMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_vmem_XMemory
 * Method:    nativeReserveByteBufferMemory
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_lib_vmem_XMemory_nativeReserveByteBufferMemory
  (JNIEnv *, jobject, jint);

/*
 * Class:     lib_vmem_XMemory
 * Method:    nativeCreateByteBuffer
 * Signature: (JI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_lib_vmem_XMemory_nativeCreateByteBuffer
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     lib_vmem_XMemory
 * Method:    initialize
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_lib_vmem_XMemory_initialize
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     lib_vmem_XMemory
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_lib_vmem_XMemory_nativeFree
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
